"""Render the maintenance publication from the fixed cohort's audited counts."""
import argparse,json
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--metrics',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--figure',default='');a=p.parse_args()
m=json.loads(a.metrics.read_text());arms=m['arms'];fixed=arms['fixed75'];mir=arms['mir75'];stop=arms['stop75'];ex=m['explicit']
frac=lambda d:f"{d['complete']}/{d['total']}"
lines=['# Maintaining complete workflows through recurring learning','',
       'Third-phase findings for [experience selection](README.md). Both earlier publications remain preserved.','',
       '## Result','',
       f"Across two prospectively fixed fresh runs, a development-tuned fixed mixture completed **{frac(fixed['all'])}** post-arrival workflows. Damage-aware replay completed **{frac(mir['all'])}** at the same actual update and target-token budgets. Both used 75% replay. The fixed stopping schedule completed **{frac(stop['all'])}** with half as many maintenance updates. The explicit archive reference completed **{ex['success']}/{ex['total']}** with no learning updates.",'']
if fixed['all']==mir['all']:
 lines+=['Damage-aware replay added no complete-task accuracy over the strong fixed mixture in this cohort. Its virtual updates and loss scoring added work. This is a local result for the tested MIR-inspired implementation, not a general result against adaptive replay.','']
elif mir['all']['complete']<fixed['all']['complete']:
 lines+=['The tested damage-aware policy did not improve complete-task accuracy over the strong fixed mixture and required additional selection work. The conclusion is limited to this workload and implementation.','']
if stop['all']['complete']==fixed['all']['complete']==fixed['all']['total']:
 lines+=['Once the first three arrivals had been learned, unconditionally stopping updates preserved complete behavior through the recurring suffix. The saving comes from a fixed stopping schedule on unchanged, already observed rules; it does not require predicting update damage.','']
else:
 lines+=['The stopping control uses a fixed schedule regardless of whether acquisition succeeded. Its accuracy and smaller update count must be considered together; fewer updates alone are not a useful-cost advantage.','']
if a.figure:lines += [f'![Complete workflow trajectories]({a.figure})','']
lines += ['## Fresh complete-task outcomes','', '| Policy | Acquisition prefix | Recurring suffix | All uses | Final | Lost before/after outcomes |','|---|---:|---:|---:|---:|---:|']
labels={'none':'No maintenance','fixed75':'Fixed 75% replay','mir75':'Damage-aware 75% replay','stop75':'Fixed replay, then stop'}
for arm,d in arms.items():lines += [f"| {labels[arm]} | {frac(d['acquisition'])} | {frac(d['recurrence'])} | {frac(d['all'])} | {frac(d['final'])} | {d['pairs']['lost']} |"]
lines += [f"| Explicit archive | 72/72 | 96/96 | {ex['success']}/{ex['total']} | 32/32 | — |",'',
'The sequence introduces birch, cedar and dune after an acquired alder state, then repeats those three arrivals. Every arrival scores all seen sites. The 168 outcomes contain repeated uses of **32 distinct later-ticket requests**, eight rule cells and two initializations. They are not 168 independent task draws. Freshness concerns new tickets and initializations under unchanged rules.','',
'| Seed | Initial alder acquisition | No maintenance final | Fixed final | Damage-aware final | Stop final |','|---|---:|---:|---:|---:|---:|']
for seed in m['seeds']:
 initial=next(s for s in seed['initial_acquisition'] if s['suite']=='later')
 vals=[]
 for arm in ['none','fixed75','mir75','stop75']:
  s=next(s for s in seed['scores'] if s['arm']==arm and s['episode']==6);vals.append(f"{s['success']}/{s['total']}")
 lines += [f"| {seed['seed']} | {initial['success']}/{initial['total']} | "+' | '.join(vals)+' |']
lines += ['', '## Workload and access','',
'A dispatch requires three ordered actions: reserve an eligible resource, perform its required preparation, and ship. Success requires the complete resulting inventory, preparation, cleared reservation and shipment state, with no invalid action. Resource and preparation scores diagnose errors but never replace complete success. Actions are scoped to the current parcel; ticket copying is not required. Each dispatch starts with its own full inventory, so the experiment measures state changes within jobs rather than one persistent inventory across jobs.','',
'There are four sites and two parcel kinds, eight rule cells and four valid action traces. Sixteen checked training tickets cover each cell; two disjoint later tickets per cell are scored in each fresh run. All historical rules remain correct. This is a small structured sandbox, not broad real-agent workflow generalization.','',
'Each learned policy starts from the same alder-only adapter constructed with 128 updates. The calibration adapter that learned all sites is not reused. Optimizers reset each arrival; later weights diverge as consequences of policy history. Targets, loss and initial states are matched. Every target has five tokens including EOS; exact prompt-token differences remain in the cost table.','',
'The selector ranks a sample of up to 16 old archive records by target-loss increase after one virtual incoming AdamW step, using cloned current optimizer moments. It reselects every 16 actual updates and cycles through the top half of candidates on replay slots. Exact restoration, optimizer isolation and equality between the virtual step and next real incoming step are checked. This adapts [MIR](sources/maintenance-mir/README.md); it is not a replication of the original image-classifier implementation.','',
'All policies can access the same checked archive and paired verification results. The selector uses archive labels, not later-case scores, to choose replay. The explicit reference retrieves a successful trace by the structured site/kind key and executes it through the identical sandbox. It receives no future-site rows before arrival. The key schema and the ticket’s irrelevance are designed knowledge. Labels and the checker are privileged synthetic supervision; real annotation and verification costs were not measured.','',
'## Development and diagnosis','',
'Initial training with two tickets per cell memorized 16/16 examples at 512 updates but completed only 3/8 unseen-ticket workflows. Increasing diversity to sixteen tickets per cell yielded 4/8 at 512 updates and **8/8 at 1,024**, with 128/128 training success. This establishes a functioning acquisition regime; it does not prove that diversity is necessary at the longer duration. Failed attempts are preserved.','',
'At 128 maintenance updates per arrival, incoming-only learned each new site and lost the previous one. The best fixed mixture (75% replay) completed 16/18 uses, whereas damage-aware 50% replay completed 7/18. We then tested a longer duration and matched replay fraction before making fresh claims.','',
'| Development updates per arrival | Fixed 25% | Fixed 50% | Fixed 75% | Damage-aware 50% | Damage-aware 75% |','|---:|---:|---:|---:|---:|---:|','| 128 | 7/18 | 10/18 | 16/18 | 7/18 | — |','| 256 | — | — | 18/18 | 17/18 | 18/18 |','',
'The longer, matched-fraction comparison resolves the initial selector floor: this implementation can maintain complete development behavior. It also shows that a fixed mixture suffices. The strongest tested selector, fixed comparator, 256-update duration, stopping control, two seeds and six-arrival sequence were committed in [the fresh protocol](protocol/maintenance-fresh-v1.md) at `ba91a06` before any fresh case generation. All seeds and checkpoints are retained; fresh outcomes did not select a replacement policy.','',
'## Costs','',
'Costs below sum the two fresh scenarios for one deployed policy. Each learned policy additionally pays **256 construction updates**. Construction was executed once per seed in the paired experiment. Before-update generations and checkpoint replay are research diagnostics; neither fixed policies nor the MIR loss scorer need those generation calls when deployed.','',
'| Policy | Maintenance updates | Virtual updates | Labeled scoring forwards | Training input / target tokens | Inclusive selection seconds | Training seconds |','|---|---:|---:|---:|---:|---:|---:|']
for arm,d in arms.items():
 c=d['costs'];u=c['update'];v=c['virtual_update'];s=c['selection_loss']
 lines += [f"| {labels[arm]} | {u['count']} | {v['count']} | {s['count']} | {u['input_tokens']} / {u['target_tokens']} | {c['selection_total_seconds']:.2f} | {u['seconds']:.2f} |"]
lines += ['', '| Policy | Later prompt / output tokens | Later generation seconds |','|---|---:|---:|']
for arm,d in arms.items():
 c=d['costs']['use_generation'];lines += [f"| {labels[arm]} | {c['prompt_tokens']} / {c['completion_tokens']} | {c['seconds']:.2f} |"]
c=mir['costs'];lines += ['',
 f"Damage-aware scoring additionally processes {c['selection_loss']['input_tokens']} input tokens and {c['selection_loss']['target_tokens']} labeled target tokens; its virtual updates process {c['virtual_update']['input_tokens']} / {c['virtual_update']['target_tokens']}. These are distinct from actual training. Whole-selection time includes cloning, hashing, virtual training, scoring, ranking and restoration, so component timings must not be added again. Token counts are not FLOPs.",'',
 f"The explicit reference stores {ex['unique_archive_rows']} checked records across the two scenarios, with {ex['serialized_archive_bytes_per_run']} serialized archive bytes per run. It performs {ex['retrieval_comparisons']} lookup comparisons and emits {ex['action_tokens']} action tokens. Measured in-memory lookup plus execution totals {ex['seconds']:.6f} seconds; archive construction totals {ex['archive_build_seconds']:.6f} seconds. Those timings exclude persistent-disk access, Python object overhead and real annotation. A saved adapter is {fixed['costs']['adapter_bytes_per_run'][0]} bytes, in addition to the common foundation model.",'',
 f"Actually executing all counterfactual branches and virtual updates costs **{m['actual_execution']['optimizer_updates']} optimizer steps**, plus diagnostics, replay checks and generation. Fresh run timers sum to **{m['actual_execution']['seconds']:.2f} seconds**, with peak MLX allocation **{m['actual_execution']['peak_mlx_bytes']} bytes**. [Resource notes](notes/resource-use.md) record shared-device coordination; these are observed timings, not isolated-hardware latency or a general amortization claim.",'',
'## Interpretation and limits','',
'The study separates complete acquisition, repeated use and maintenance. End-of-sequence success alone would hide failures during the acquisition prefix. Correct archive records can remain useful rehearsal, but selecting records with predicted loss increases is not automatically more useful than a tuned fixed mixture. A fixed stopping schedule is a separate explanation for savings when repeated arrivals introduce no new rules.','',
'The explicit reference demonstrates the strength of an accessible, sufficient structured archive in this sandbox. It does not establish a universal choice between weights and retrieval. Likewise, the comparison does not test novel-rule generalization, changing historical rules, a learned abstention gate, optimized batched MIR implementations, long-horizon agent behavior or globally minimal training budgets.','',
'## Evidence and reproduction','',
 f"The [aggregate metrics]({a.metrics.as_posix()}) link to [per-run audited metrics](evidence/maintenance-fresh-v1-audit/metrics.json). Raw runs preserve prompts, token IDs, state outcomes, every update and selection, evaluated adapters, exact reload checks, source snapshots and manifests. The auditor checks historical-only candidate access, complete evaluation membership, matched starts, frozen-prefix checkpoint equality, disjoint development/fresh tickets and byte-identical policy/protocol snapshots against `ba91a06`.",'',
'[Methods](notes/maintenance-methods.md), [development log](notes/maintenance-development.md), [reproduction](notes/maintenance-reproduction.md), and [primary implementation provenance](sources/maintenance-mir/README.md) provide the full specification. Qwen3-4B-Instruct-2507 revision `cdbee75f17c01a7cc42f958dc650907174af0554`; MLX-LM revision `86b48c461feebf87c58788655b7e57b5574b9e6d`; exact environment in `uv.lock` and run resource records. No teacher distributions are used.','']
a.output.write_text('\n'.join(lines))
